services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: backend-llm
    ports:
      - "8033:8000"
    env_file:
      - .env
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    build:
      context: ./chat
    container_name: frontend-llm
    ports:
      - "3033:3000"
    networks:
      - app-net

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.1
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
